
model:
  n_blocks: 4
  levels: 2
  dim: 36
  window_size: 8
  scale_factor: 2.0


training:
  epochs: 100
  batch_size: 4
  accumulation_steps: 4
  learning_rate: 0.001
  testing_data_split: 0.1
  image_height: 1920
  image_width: 1080
  training_scale_factor: 4.0
  log: True
  model_save_location: ""
  perceptual_loss_scale: 0.1

