model:
  n_blocks: 8
  levels: 4
  dim: 60
  window_size: 8
  scale_factor: 4

training:
  is_training: False
  epochs: 200
  batch_size: 1
  accumulation_steps: 1
  learning_rate: 0.001
  testing_data_split: 0.1
  image_height: 1920
  image_width: 1080
  perceptual_loss_scale: 0.01
  fft_loss_scale: 0.01

tools:
  log: False
  model_save_directory: "Model Saves"
  load_model_directory: "model_save_epoch_49.pth" 
  save_model_every_i_epoch: 1

