model:
  n_blocks: 8
  levels: 4
  dim: 60
  window_size: 8
  scale_factor: 4

training:
  is_training: True
  epochs: 200
  batch_size: 2
  accumulation_steps: 16
  learning_rate: 0.002
  testing_data_split: 0.1
  image_height: 1080
  image_width: 1920
  perceptual_loss_scale: 0.03
  fft_loss_scale: 0.05

tools:
  log: True
  model_save_directory: "Model Saves"
  load_model_save_name: ""
  save_model_every_i_epoch: 1

