
model:
  n_blocks: 8
  levels: 4
  dim: 60
  window_size: 8
  scale_factor: 4


training:
  epochs: 100
  batch_size: 1
  accumulation_steps: 2
  learning_rate: 0.001
  testing_data_split: 0.1
  image_height: 1920
  image_width: 1080
  perceptual_loss_scale: 0.1
  fft_loss_scale: 0.1


tracking_tools:
  log: False
  model_save_location: "Model Saves"
  save_model_every_i_epoch: 0

