model:
  scale_factor: 4
  block_type: "default"
  n_blocks: 6
  n_sub_blocks: 4
  levels: 3
  dim: 128
  level_dim: 96
  n_heads: 4
  n_heads_fuse: 4
  feature_dim: 64
  window_size: 16


training:
  learning_rate: 0.00015
  batch_size_per_gpu: 32
  accumulation_steps: 1
  iterations: 500000
  epochs: 100
  model_ema: 0.999
  ema_start_epoch: 3
  criterion:
    L1: 1.0
    #FFTLoss: 0.05

dataset:
  data_root: "data"
  num_dataloader_workers: 32

  training:
    file_name: "train"
    use_sub_images: True
    paired_images: True
    random_rot: True
    random_flip: True
    data_subset_size: 0
    dataset_enlarge_scale: 1
    crop_size: 256

  validation:
    file_name: "test"
    data_subset_size: 0
    crop_size: 512

tools:
  file_backend_type: "Disk"
  prefetching_dataloader: False
  multi_gpu_enable: False
  pretrained_weights_path: ""
  load_optimizer: True
  benchmark: True
  deterministic: False

logging:
  wandb_log: True
  path: "Logs"
  save_model_every_i_epoch: 1
  model_save_name: ""
  sub_img_col: 4
  sum_img_row: 2

